<Project Sdk="Godot.NET.Sdk/4.5.0">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>SourceGenDebug</RootNamespace>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <AdditionalFiles Include="project.godot" Visible="false" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GodotGenerator.Attributes\Attributes.csproj" OutputItemType="Analyzer" />
    <ProjectReference Include="..\GodotGenerator.Generators\Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>